# Generated by Django 5.0.7 on 2024-09-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_orderitem'),
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='items',
            field=models.ManyToManyField(related_name='delivery_orders', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='removed_ingredients',
            field=models.ManyToManyField(blank=True, related_name='removed_from_order_items', to='menu.ingredient'),
        ),
    ]
