# Generated by Django 5.0.7 on 2024-09-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryorder_items_alter_deliveryorder_order_and_more'),
        ('restaurant', '0006_delete_deliveryorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order'),
        ),
    ]
