# Generated by Django 5.0.7 on 2024-09-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_deliveryorder_order_alter_orderitem_order'),
        ('restaurant', '0006_delete_deliveryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.order'),
        ),
    ]
