# Generated by Django 5.0.7 on 2024-09-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryorder_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='user',
        ),
    ]
