# Generated by Django 5.0.7 on 2024-09-21 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_deliveryorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='restaurant_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
