# Generated by Django 5.0.7 on 2024-09-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_deliveryorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('canceled', 'Cancelado')], default='pending', max_length=10),
        ),
    ]
