# Generated by Django 5.0.7 on 2024-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='cep',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
