# Generated by Django 5.0.7 on 2024-09-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='restaurant_accepted',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
