# Generated by Django 5.0.7 on 2024-09-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_remove_deliveryorder_cep_and_more'),
        ('restaurant', '0011_table_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
