# Generated by Django 5.0.7 on 2024-09-23 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_deliveryorder_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 23, 20, 47, 40, 854360, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
