# Generated by Django 5.0.7 on 2024-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_deliveryorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='cep',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
