# Generated by Django 5.0.7 on 2024-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_deliveryorder_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('canceled', 'Cancelado')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
