# Generated by Django 5.0.7 on 2024-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_deliveryorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('canceled', 'Cancelado')], default='pending', max_length=15),
        ),
    ]
