# Generated by Django 5.0.7 on 2024-09-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_remove_notification_restaurant_notification_order_and_more'),
        ('restaurant', '0013_restaurant_delivery_time_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
