# Generated by Django 5.0.7 on 2024-09-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_notification_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
