# Generated by Django 5.0.7 on 2024-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_deliveryorder_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='observation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
