# Generated by Django 5.0.7 on 2024-10-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_deliveryorder_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
