# Generated by Django 5.0.7 on 2024-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_deliveryorder_is_local_alter_deliveryorder_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
