# Generated by Django 5.0.7 on 2024-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_alter_deliveryorder_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
