# Generated by Django 5.0.7 on 2024-08-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_menu_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], max_length=10, null=True),
        ),
    ]
