# Generated by Django 5.0.7 on 2024-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
