# Generated by Django 5.0.7 on 2024-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_menu_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(related_name='orders', to='core.menu')),
            ],
        ),
    ]
