# Generated by Django 5.0.7 on 2024-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_is_delivery_alter_order_is_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
