# Generated by Django 5.0.7 on 2024-08-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_orderitem_is_delivery_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='delivery_order',
                to='core.order',
                null=True,  
                blank=True 
            ),
        ),
    ]
