# Generated by Django 5.0.7 on 2024-08-10 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deliveryorder_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('cnpj', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('phone_number', models.CharField(max_length=15)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='restaurant',
            field=models.ForeignKey(
                null=True,  
                blank=True,  
                on_delete=django.db.models.deletion.CASCADE,
                related_name='delivery',
                to='core.restaurant'
            ),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='menus',
                to='core.restaurant'
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter', to='core.restaurant'),
            preserve_default=False,
        ),
    ]
