# Generated by Django 5.0.7 on 2024-08-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_owner_restaurant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
