# Generated by Django 5.0.7 on 2024-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_table_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
