# Generated by Django 5.0.7 on 2024-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restaurant_delivery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_tax',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
