# Generated by Django 5.0.7 on 2024-08-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_restaurant_delivery_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='delivery_tax',
            new_name='delivery_rate_per_km',
        ),
    ]
