# Generated by Django 5.0.7 on 2024-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_delivery_tax_restaurant_delivery_rate_per_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
