# Generated by Django 5.0.7 on 2024-08-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='menu_images/avatar_restaurant.webp', upload_to='menu_images/'),
        ),
    ]
