# Generated by Django 5.0.7 on 2024-08-13 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_restaurant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_closing_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_opening_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
