# Generated by Django 5.0.7 on 2024-08-13 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_restaurant_delivery_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_closing_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_opening_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
