# Generated by Django 5.0.7 on 2024-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_restaurant_delivery_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
