# Generated by Django 5.0.7 on 2024-08-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subscription_next_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='method_payment',
            field=models.CharField(choices=[('basic', 'Pix'), ('premium', 'Cartão')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
