# Generated by Django 5.0.7 on 2024-08-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_subscription_method_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='method_payment',
            field=models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão')], max_length=10),
        ),
    ]
