# Generated by Django 5.0.7 on 2024-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_subscription_method_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
