# Generated by Django 5.0.7 on 2024-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_subscription_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Campo Grande', max_length=255),
        ),
    ]
