# Generated by Django 5.0.7 on 2024-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='preapproval_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
