# Generated by Django 5.0.7 on 2024-09-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_subscription_preapproval_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='preapproval_id',
        ),
    ]
