# Generated by Django 5.0.7 on 2024-09-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_subscription_preapproval_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
