# Generated by Django 5.0.7 on 2024-09-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_delete_deliveryorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
