# Generated by Django 5.0.7 on 2024-09-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_orderitem'),
        ('delivery', '0003_alter_deliveryorder_items_alter_deliveryorder_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
