# Generated by Django 5.0.7 on 2024-09-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
