# Generated by Django 5.0.7 on 2024-09-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
