# Generated by Django 5.0.7 on 2024-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
