# Generated by Django 5.0.7 on 2024-09-16 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], max_length=10, null=True)),
                ('is_accept_restaurant', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('anddres', models.CharField(max_length=40)),
                ('cep_customer', models.CharField(max_length=9)),
                ('complement_anddres', models.CharField(max_length=20)),
                ('total_order', models.DecimalField(decimal_places=2, max_digits=5)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
