# Generated by Django 5.0.7 on 2024-09-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_deliveryorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
