# Generated by Django 5.0.7 on 2024-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_delete_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='default_printer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
