# Generated by Django 5.0.7 on 2024-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_default_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
