# Generated by Django 5.0.7 on 2024-09-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_remove_deliveryorder_cep_and_more'),
        ('menu', '0002_menu_restaurant'),
        ('restaurant', '0009_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='delivery.deliveryorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='removed_ingredients',
            field=models.ManyToManyField(blank=True, related_name='removed_from_order_items', to='menu.ingredient'),
        ),
    ]
