# Generated by Django 5.0.7 on 2024-09-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_table_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
