# Generated by Django 5.0.7 on 2024-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_waiter_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time_in_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Tempo de entrega em minutos'),
        ),
    ]
