# Generated by Django 5.0.7 on 2024-09-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_restaurant_delivery_time_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_print',
            field=models.BooleanField(default=False),
        ),
    ]
