# Generated by Django 5.0.7 on 2024-09-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_order_order_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurant', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
